Updated checkpoint

diff --git a/bin/runbench b/bin/runbench
--- a/bin/runbench
+++ b/bin/runbench
@@ -1,15 +1,18 @@
 #!/bin/bash
 
-BENCH_BASE=${HOME}/projects/AI-PROJECTS/experimental/install/venv-build-checker
+[ -L "${BASH_SOURCE[0]}" ] && THIS_SCRIPT=$(readlink -f "${BASH_SOURCE[0]}") || THIS_SCRIPT="${BASH_SOURCE[0]}"
+
+MY_NAME=$(basename ${THIS_SCRIPT} )
+MY_BIN=$(dirname ${THIS_SCRIPT})
+MY_BASE=$(dirname ${THIS_SCRIPT})
+MY_ARGS=$*
+MY_INCLUDE=$( ( [ -d "${MY_BIN}/shinclude" ] && echo "${MY_BIN}/shinclude" ) || echo "${HOME}/shinclude" )
+
+# Source in some useful shortcut functions for VENV management.
+[ -f ${MY_INCLUDE}/init_env.sh ] && . ${MY_INCLUDE}/init_env.sh \
+    || ( echo "${MY_NAME}: Could not find init_env.sh in INCLUDEDIR: ${MY_INCLUDE}"; exit 1 )
 
 export PATH=${BENCH_BASE}/bin:${PATH}
-
-CONDA_ROOT=${_CONDA_ROOT:-$(conda info -s | grep CONDA_ROOT | cut -d " " -f 2)}
-[ -e ${CONDA_ROOT}/bin/activate ] && . ${CONDA_ROOT}/bin/activate \
-                                  || ( echo "Conda environment not found! Check your environment for Conda." && exit 1 )
-
-. ${BENCH_BASE}/bin/shinclude/venv-funcs.sh
-
 
 ( vm_stat 1 | filter-vm_stat -d -s ) &
 
